export type CandidateSource =
  | "module-replacements"
  | "deprecated"
  | "node-builtin"
  | "polyfill-decay";

export type ReplacementType = "native" | "simple" | "documented" | "remove";
export type PackageStatus = "archived" | "dormant" | "stale" | "active";
export type Tier = 1 | 2 | 3 | 4;

export interface LeaderboardEntry {
  rank: number;
  moduleName: string;
  source: CandidateSource;
  replacementType: ReplacementType;
  replacement: string;
  weeklyDownloads: number;
  dependentCount: number;
  compositeScore: number;
  impactScore: number;
  effortMultiplier: number;
  mergeProbability: number;
  livenessPenalty: number;
  tier: Tier;
  status: PackageStatus;
  repoUrl: string | null;
  topDependents: Array<{ name: string; downloads: number }>;
}

export interface Stats {
  lastUpdated: string;
  totalPackages: number;
  totalDownloadsRepresented: number;
  activeOpportunities: number;
  bySource: Record<CandidateSource, number>;
  byTier: Record<string, number>;
  byStatus: Record<PackageStatus, number>;
}

// Static imports at build time — these files are generated by the analyzer pipeline
import leaderboardData from "../../../../public/e18e/api/leaderboard.json";
import statsData from "../../../../public/e18e/api/stats.json";

export const leaderboard = leaderboardData as LeaderboardEntry[];
export const stats = statsData as Stats;
