export const TILE_SIZE = 64;
export const MAP_COLS = 16;
export const MAP_ROWS = 12;
export const CANVAS_WIDTH = MAP_COLS * TILE_SIZE;  // 1024
export const CANVAS_HEIGHT = MAP_ROWS * TILE_SIZE; // 768
export const MOVE_SPEED = 3; // pixels per frame
export const ANIMATION_FRAME_DURATION = 135; // ms per walk frame (Mana Seed guide)
export const INTERACTION_RANGE = 1; // tiles
export const SPAWN_X = 8; // tile column (center of 16-col map)
export const SPAWN_Y = 8; // tile row (lower-center)
export const PLAYER_SCALE = 2; // character sprite scale multiplier
